In [1]:
!pip install pandas python-dotenv groq

Requirement already satisfied: pandas in ./env/lib/python3.12/site-packages (3.0.2)
Requirement already satisfied: python-dotenv in ./env/lib/python3.12/site-packages (1.2.2)
Requirement already satisfied: groq in ./env/lib/python3.12/site-packages (1.2.0)
Requirement already satisfied: numpy>=1.26.0 in ./env/lib/python3.12/site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in ./env/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: anyio<5,>=3.5.0 in ./env/lib/python3.12/site-packages (from groq) (4.13.0)
Requirement already satisfied: distro<2,>=1.7.0 in ./env/lib/python3.12/site-packages (from groq) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in ./env/lib/python3.12/site-packages (from groq) (0.28.1)
Requirement already satisfied: pydantic<3,>=1.9.0 in ./env/lib/python3.12/site-packages (from groq) (2.13.3)
Requirement already satisfied: sniffio in ./env/lib/python3.12/site-packages (from groq) (1.3.1)
Requirement already satisfied: typing-extensions<5,>=4.14 in ./env/lib/python3.12/site-packages (from groq) (4.15.0)
Requirement already satisfied: idna>=2.8 in ./env/lib/python3.12/site-packages (from anyio<5,>=3.5.0->groq) (3.13)
Requirement already satisfied: certifi in ./env/lib/python3.12/site-packages (from httpx<1,>=0.23.0->groq) (2026.4.22)
Requirement already satisfied: httpcore==1.* in ./env/lib/python3.12/site-packages (from httpx<1,>=0.23.0->groq) (1.0.9)
Requirement already satisfied: h11>=0.16 in ./env/lib/python3.12/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->groq) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in ./env/lib/python3.12/site-packages (from pydantic<3,>=1.9.0->groq) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.3 in ./env/lib/python3.12/site-packages (from pydantic<3,>=1.9.0->groq) (2.46.3)
Requirement already satisfied: typing-inspection>=0.4.2 in ./env/lib/python3.12/site-packages (from pydantic<3,>=1.9.0->groq) (0.4.2)
Requirement already satisfied: six>=1.5 in ./env/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.0.1 -> 26.1
[notice] To update, run: pip install --upgrade pip

In [2]:
import pandas as pd
import os
from dotenv import load_dotenv
from groq import Groq
from IPython.display import display

load_dotenv()

api_key = os.getenv("GROQ_API_KEY")

if not api_key:
    raise ValueError("GROQ_API_KEY not found in .env")

client = Groq(api_key=api_key)

In [3]:
# Load the dataset (Task - 1)
df = pd.read_csv("patient_data.csv")


print("Dataset Shape:", df.shape)
df.head()

Dataset Shape: (100, 18)

,patient_id,patient_name,age,gender,diagnosis,current_medication,lab_test,lab_value,lab_unit,last_visit_date,next_scheduled_visit,days_since_last_visit,missed_last_appointment,vitals_bp_systolic,vitals_bp_diastolic,vitals_heart_rate,vitals_spo2,notes
0,P0001,Aarav Sharma,68,Male,Type 2 Diabetes,Metformin 500mg,HbA1c,9.9,%,2024-04-24,2024-06-08,251,No,174,70,95,96,Patient reports good medication adherence.
1,P0002,Priya Patel,29,Male,Heart Failure,Furosemide 40mg,BNP,317.6,pg/mL,2024-01-14,2024-02-28,352,No,174,91,72,97,Patient reports no new symptoms.
2,P0003,Rohan Mehta,45,Male,"Type 2 Diabetes, CKD","Insulin Glargine 10U, Losartan 50mg",HbA1c,11.4,%,2024-08-04,2024-10-03,149,No,132,86,64,91,Medication dose adjusted this visit.
3,P0004,Anjali Singh,34,Female,"COPD, Heart Failure","Tiotropium 18mcg, Furosemide 40mg",FEV1%,33.8,%,2024-01-23,2024-04-22,343,No,153,70,93,94,Patient reports no new symptoms.
4,P0005,Vikram Nair,51,Male,"Hypertension, Heart Failure","Amlodipine 5mg, Furosemide 40mg",BP Systolic,124.9,mmHg,2024-04-26,2024-06-25,249,No,134,71,82,94,Patient education provided on diet and lifestyle.

In [4]:
df.describe()

,age,lab_value,days_since_last_visit,vitals_bp_systolic,vitals_bp_diastolic,vitals_heart_rate,vitals_spo2
count,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
mean,55.360000,150.810000,211.390000,145.570000,87.680000,82.420000,94.500000
std,15.251773,279.918492,87.498675,20.375889,13.625496,14.460102,2.794294
min,28.000000,1.700000,65.000000,105.000000,65.000000,58.000000,90.000000
25%,44.000000,9.675000,132.500000,130.000000,75.750000,72.000000,92.000000
50%,55.000000,34.950000,219.000000,145.500000,87.500000,83.000000,95.000000
75%,68.000000,144.600000,287.750000,161.250000,99.250000,95.000000,97.000000
max,82.000000,1164.000000,360.000000,181.000000,110.000000,108.000000,99.000000

In [5]:
df.isnull().sum()

patient_id                 0
patient_name               0
age                        0
gender                     0
diagnosis                  0
current_medication         0
lab_test                   0
lab_value                  0
lab_unit                   0
last_visit_date            0
next_scheduled_visit       0
days_since_last_visit      0
missed_last_appointment    0
vitals_bp_systolic         0
vitals_bp_diastolic        0
vitals_heart_rate          0
vitals_spo2                0
notes                      0
dtype: int64

In [6]:
def call_llm(prompt, retries=2):
    models = ["llama-3.1-8b-instant", "llama-3.3-70b-versatile"]

    for model in models:
        for attempt in range(retries):
            try:
                res = client.chat.completions.create(
                    model=model,
                    messages=[{"role": "user", "content": prompt}],
                    temperature=0.3
                )
                return res.choices[0].message.content
            except Exception as e:
                print(f"[Retry {attempt+1}] {model} failed")
                time.sleep(1)

    return "LLM ERROR"

In [7]:
# Define Agents Tools (Task - 2)
def risk_tool(patient):
    prompt = f"""
    You are a clinical AI.

    Classify risk: LOW, MEDIUM, HIGH.

    Consider:
    vitals, labs, diagnosis, missed visits.

    Patient:
    {patient}

    Output:
    Risk + short reason
    """
    return call_llm(prompt)

In [8]:
def action_tool(patient, risk):
    prompt = f"""
    Create a follow-up plan.

    Risk: {risk}

    Include:
    urgency, actions, timeline.

    Patient:
    {patient}
    """
    return call_llm(prompt)

In [9]:
def missed_tool(patient):
    prompt = f"""
    Patient missed appointment.

    Provide:
    outreach, risk, next steps.

    Patient:
    {patient}
    """
    return call_llm(prompt)

In [10]:
# Agent Decision (Task -3)
def agent_decision(patient):
    prompt = f"""
    You are an AI agent.

    Tools:
    - risk_tool
    - action_tool
    - missed_tool

    Patient:
    {patient}

    Decide best tool.

    Output:
    TOOL: <name>
    """
    return call_llm(prompt).lower()

In [11]:
def run_agent(patient):
    decision = agent_decision(patient)

    if "risk_tool" in decision:
        risk = risk_tool(patient)
        plan = action_tool(patient, risk)
        return {"risk": risk, "plan": plan}

    elif "missed_tool" in decision:
        follow = missed_tool(patient)
        return {"followup": follow}

    else:
        return {"message": "No action"}

In [12]:
def agent_decision(patient):
    prompt = f"""
    You are an AI agent.

    Tools:
    - risk_tool
    - action_tool
    - missed_tool

    Patient:
    {patient}

    Decide best tool.

    Output:
    TOOL: <name>
    """
    return call_llm(prompt).lower()

In [13]:
def run_agent(patient):
    decision = agent_decision(patient)

    if "risk_tool" in decision:
        risk = risk_tool(patient)
        plan = action_tool(patient, risk)
        return {"risk": risk, "plan": plan}

    elif "missed_tool" in decision:
        follow = missed_tool(patient)
        return {"followup": follow}

    else:
        return {"message": "No action"}

In [14]:
#Single Patient (Task -4)
patient = df.iloc[8].to_dict()

result = run_agent(patient)

print("Patient:", patient["patient_name"])
print(result)

Patient: Amit Joshi
{'risk': "Based on the provided patient data, I would classify the risk as:\n\n**MEDIUM**\n\nReason: Elevated blood pressure (BP Systolic: 159.3 mmHg) and recent missed appointment (66 days since last visit) indicate a moderate level of risk. The patient's diagnosis of Hypertension and Heart Failure also contributes to this classification. However, the patient's current medication and lab values suggest that their condition is being managed, but more frequent monitoring is necessary to prevent complications.\n\nNote: A more detailed analysis would be required to provide a more accurate risk assessment, but based on the provided data, a medium risk classification seems appropriate.", 'plan': "**Follow-up Plan for Patient P0009 (Amit Joshi)**\n\n**Risk Classification:** Medium\n\n**Reason:** Elevated blood pressure (BP Systolic: 159.3 mmHg) and recent missed appointment (66 days since last visit) indicate a moderate level of risk. The patient's diagnosis of Hypertension and Heart Failure also contributes to this classification. However, the patient's current medication and lab values suggest that their condition is being managed, but more frequent monitoring is necessary to prevent complications.\n\n**Urgency:** High\n\n**Actions:**\n\n1. **Schedule an immediate appointment**: Book an appointment for the patient as soon as possible, ideally within the next 7-10 days.\n2. **Review current medication**: Assess the patient's current medication regimen and make adjustments as necessary to ensure optimal management of their Hypertension and Heart Failure.\n3. **Conduct a thorough physical examination**: Perform a comprehensive physical examination to assess the patient's overall health and identify any potential complications.\n4. **Order additional lab tests**: Schedule lab tests to monitor the patient's kidney function, electrolyte levels, and other relevant parameters.\n5. **Await specialist report**: Follow up with the specialist to obtain their report and incorporate their recommendations into the patient's care plan.\n6. **Develop a comprehensive care plan**: Create a personalized care plan that addresses the patient's specific needs and goals, including regular monitoring, medication adjustments, and lifestyle modifications.\n\n**Timeline:**\n\n* **Within the next 7-10 days**: Schedule an immediate appointment for the patient and conduct a thorough physical examination.\n* **Within the next 14-21 days**: Order additional lab tests and await the results.\n* **Within the next 30 days**: Review the patient's lab results and adjust their medication regimen as necessary.\n* **Within the next 60 days**: Schedule a follow-up appointment to reassess the patient's progress and make any necessary adjustments to their care plan.\n\n**Monitoring and Follow-up:**\n\n* **Regular blood pressure monitoring**: Schedule regular blood pressure checks to monitor the patient's response to treatment.\n* **Kidney function monitoring**: Schedule regular lab tests to monitor the patient's kidney function and adjust their medication regimen as necessary.\n* **Electrolyte level monitoring**: Schedule regular lab tests to monitor the patient's electrolyte levels and adjust their medication regimen as necessary.\n* **Follow-up appointments**: Schedule regular follow-up appointments to reassess the patient's progress and make any necessary adjustments to their care plan."}

In [15]:
def format_output(patient, result):
    print("\n" + "="*60)
    print(f"Patient: {patient['patient_name']}")
    print("="*60)

    print("\n Risk Assessment")
    print("-"*60)
    print(result['risk'])

    print("\n Follow-up Plan")
    print("-"*60)
    print(result['plan'])
    print("="*60)


format_output(patient, result)

============================================================
Patient: Amit Joshi
============================================================

 Risk Assessment
------------------------------------------------------------
Based on the provided patient data, I would classify the risk as:

**MEDIUM**

Reason: Elevated blood pressure (BP Systolic: 159.3 mmHg) and recent missed appointment (66 days since last visit) indicate a moderate level of risk. The patient's diagnosis of Hypertension and Heart Failure also contributes to this classification. However, the patient's current medication and lab values suggest that their condition is being managed, but more frequent monitoring is necessary to prevent complications.

Note: A more detailed analysis would be required to provide a more accurate risk assessment, but based on the provided data, a medium risk classification seems appropriate.

 Follow-up Plan
------------------------------------------------------------
**Follow-up Plan for Patient P0009 (Amit Joshi)**

**Risk Classification:** Medium

**Reason:** Elevated blood pressure (BP Systolic: 159.3 mmHg) and recent missed appointment (66 days since last visit) indicate a moderate level of risk. The patient's diagnosis of Hypertension and Heart Failure also contributes to this classification. However, the patient's current medication and lab values suggest that their condition is being managed, but more frequent monitoring is necessary to prevent complications.

**Urgency:** High

**Actions:**

1. **Schedule an immediate appointment**: Book an appointment for the patient as soon as possible, ideally within the next 7-10 days.
2. **Review current medication**: Assess the patient's current medication regimen and make adjustments as necessary to ensure optimal management of their Hypertension and Heart Failure.
3. **Conduct a thorough physical examination**: Perform a comprehensive physical examination to assess the patient's overall health and identify any potential complications.
4. **Order additional lab tests**: Schedule lab tests to monitor the patient's kidney function, electrolyte levels, and other relevant parameters.
5. **Await specialist report**: Follow up with the specialist to obtain their report and incorporate their recommendations into the patient's care plan.
6. **Develop a comprehensive care plan**: Create a personalized care plan that addresses the patient's specific needs and goals, including regular monitoring, medication adjustments, and lifestyle modifications.

**Timeline:**

* **Within the next 7-10 days**: Schedule an immediate appointment for the patient and conduct a thorough physical examination.
* **Within the next 14-21 days**: Order additional lab tests and await the results.
* **Within the next 30 days**: Review the patient's lab results and adjust their medication regimen as necessary.
* **Within the next 60 days**: Schedule a follow-up appointment to reassess the patient's progress and make any necessary adjustments to their care plan.

**Monitoring and Follow-up:**

* **Regular blood pressure monitoring**: Schedule regular blood pressure checks to monitor the patient's response to treatment.
* **Kidney function monitoring**: Schedule regular lab tests to monitor the patient's kidney function and adjust their medication regimen as necessary.
* **Electrolyte level monitoring**: Schedule regular lab tests to monitor the patient's electrolyte levels and adjust their medication regimen as necessary.
* **Follow-up appointments**: Schedule regular follow-up appointments to reassess the patient's progress and make any necessary adjustments to their care plan.
============================================================

In [16]:
# Missed Appointments (Task -5)
missed_df = df[df["missed_last_appointment"] == "Yes"]

outputs = []

for _, row in missed_df.iterrows():
    patient = row.to_dict()
    result = run_agent(patient)

    outputs.append({
        "patient_id": patient["patient_id"],
        "result": result
    })

print("Processed:", len(outputs))
print(outputs[:2])

Processed: 15
[{'patient_id': 'P0018', 'result': {'followup': "**Outreach Plan:**\n\n1. **Phone Call:** Reach out to the patient via phone to remind them of the missed appointment and inquire about their current health status. This will help in understanding the reason for missing the appointment and provide an opportunity to reschedule.\n2. **Email or SMS:** Send a follow-up email or SMS to the patient to confirm the missed appointment and provide a link to reschedule online.\n3. **Personalized Message:** Leave a personalized voicemail or message for the patient, addressing them by name and expressing concern about their missed appointment.\n\n**Risk Assessment:**\n\nBased on the patient's medical history and current vitals, the following risks are identified:\n\n1. **Uncontrolled Blood Pressure:** The patient's systolic blood pressure (160 mmHg) is higher than the recommended level, which may increase the risk of cardiovascular events.\n2. **Increased Heart Rate:** The patient's heart rate (85 bpm) is higher than the normal range, which may indicate underlying cardiac issues.\n3. **Missed Appointment:** The patient's history of missed appointments may indicate a lack of engagement with their healthcare, which can lead to poor health outcomes.\n\n**Next Steps:**\n\n1. **Reschedule Appointment:** Work with the patient to reschedule their appointment for a date and time that suits them.\n2. **Review Medication Adherence:** Discuss the patient's medication adherence with them and provide guidance on how to improve it.\n3. **Monitor Vitals:** Schedule a follow-up appointment to monitor the patient's vitals, including blood pressure and heart rate.\n4. **Patient Education:** Provide the patient with educational materials on heart failure management, including diet and lifestyle modifications.\n5. **Social Determinants of Health:** Assess the patient's social determinants of health, including access to food, transportation, and social support, to identify potential barriers to care.\n\n**Action Items:**\n\n1. Update the patient's medical record with the reason for missing the appointment and any subsequent actions taken.\n2. Document the patient's response to outreach efforts and any changes to their care plan.\n3. Schedule a follow-up appointment with the patient to monitor their progress and adjust their care plan as needed."}}, {'patient_id': 'P0031', 'result': {'followup': "**Outreach Plan:**\n\nTo address the missed appointment, consider the following outreach plan:\n\n1. **Phone Call:** Reach out to the patient via phone to inquire about the missed appointment and express concern for their health. This will help to:\n\t* Re-establish communication with the patient.\n\t* Understand the reason for missing the appointment (if any).\n\t* Provide an opportunity to reschedule the appointment.\n2. **Text Message or Email:** Send a follow-up message to the patient via text or email to:\n\t* Confirm the missed appointment.\n\t* Encourage the patient to reschedule the appointment.\n\t* Provide a link to the patient portal (if available) for easy rescheduling.\n3. **Patient Portal:** Update the patient's portal with a notification about the missed appointment and:\n\t* Provide instructions on how to reschedule the appointment.\n\t* Offer a link to schedule a new appointment online.\n\n**Risk Assessment:**\n\nConsidering the patient's diagnosis (Chronic Kidney Disease) and lab results (eGFR: 52.1 mL/min/1.73m²), there is a moderate risk of disease progression if not managed properly. The patient's missed appointment may indicate a lack of adherence to their treatment plan or a worsening of their condition.\n\n**Next Steps:**\n\n1. **Reschedule the Appointment:** Work with the patient to reschedule the appointment at the earliest convenience.\n2. **Review Medication Adherence:** Discuss the patient's current medication adherence and provide guidance on how to improve it.\n3. **Lab Test Follow-up:** Schedule a follow-up lab test to monitor the patient's kidney function and adjust their treatment plan accordingly.\n4. **Vital Sign Monitoring:** Continue to monitor the patient's vital signs, including blood pressure, heart rate, and oxygen saturation, to ensure that their condition is stable.\n5. **Patient Education:** Educate the patient on the importance of regular follow-up appointments and the potential consequences of missing appointments.\n\n**Additional Considerations:**\n\n* If the patient is experiencing any new symptoms or concerns, address them promptly and provide guidance on how to manage them.\n* Consider referring the patient to a social worker or case manager to address any social determinants of health that may be impacting their ability to attend appointments.\n* Review the patient's medical history and adjust their treatment plan as needed to ensure that they are receiving the best possible care."}}]

In [17]:
import re

def clean_text(text):
    """Remove markdown symbols and extra spaces"""
    if not text:
        return ""
    text = re.sub(r"\*\*|__|###|\*|`", "", text)   # remove markdown
    text = re.sub(r"\n+", "\n", text)              # normalize newlines
    return text.strip()


def print_patient_summary(outputs, limit=None):
    print("\n" + "="*80)
    print(" MISSED APPOINTMENTS SUMMARY")
    print("="*80)

    for i, item in enumerate(outputs):
        if limit and i >= limit:
            break

        patient_id = item.get("patient_id", "N/A")
        result = item.get("result", {})

        print(f"\n Patient ID: {patient_id}")
        print("-"*80)

        # --- Risk ---
        risk = result.get("risk")
        if risk:
            print("\n Risk Assessment:")
            print(clean_text(risk)[:400], "...")

        # --- Plan ---
        plan = result.get("plan")
        if plan:
            print("\n📋 Care Plan:")
            print(clean_text(plan)[:400], "...")

        # --- Follow-up ---
        followup = result.get("followup")
        if followup:
            print("\n Follow-up Actions:")
            print(clean_text(followup)[:400], "...")

        print("\n" + "="*80)

print_patient_summary(outputs)

================================================================================
 MISSED APPOINTMENTS SUMMARY
================================================================================

 Patient ID: P0018
--------------------------------------------------------------------------------

 Follow-up Actions:
Outreach Plan:
1. Phone Call: Reach out to the patient via phone to remind them of the missed appointment and inquire about their current health status. This will help in understanding the reason for missing the appointment and provide an opportunity to reschedule.
2. Email or SMS: Send a follow-up email or SMS to the patient to confirm the missed appointment and provide a link to reschedule onlin ...

================================================================================

 Patient ID: P0031
--------------------------------------------------------------------------------

 Follow-up Actions:
Outreach Plan:
To address the missed appointment, consider the following outreach plan:
1. Phone Call: Reach out to the patient via phone to inquire about the missed appointment and express concern for their health. This will help to:
	 Re-establish communication with the patient.
	 Understand the reason for missing the appointment (if any).
	 Provide an opportunity to reschedule the appointment.
 ...

================================================================================

 Patient ID: P0036
--------------------------------------------------------------------------------

 Risk Assessment:
Risk Classification:
Based on the provided patient information, I would classify the risk as MEDIUM.
Reason:
1. High Blood Pressure: The patient's systolic blood pressure (181 mmHg) is significantly elevated, indicating a high risk of cardiovascular disease.
2. Missed Appointment: The patient has missed their last appointment, which may indicate a lack of engagement with their care plan or a poten ...

📋 Care Plan:
Follow-up Plan:
Urgency: High
Reason: The patient has missed their last appointment, and their high blood pressure and long time since last visit indicate a need for immediate attention.
Actions:
1. Schedule a Follow-up Appointment:
	 Action: Contact the patient to schedule a follow-up appointment as soon as possible.
	 Timeline: Within the next 24-48 hours.
	 Priority: High
2. Review Medication R ...

================================================================================

 Patient ID: P0041
--------------------------------------------------------------------------------

 Follow-up Actions:
Outreach Plan:
1. Phone Call: Reach out to the patient via phone to remind them of the missed appointment and inquire about their current health status.
2. Text Message: Send a text message to the patient's registered phone number to remind them of the appointment and provide a link to reschedule.
3. Email: Send a follow-up email to the patient's registered email address to remind them of the appo ...

================================================================================

 Patient ID: P0043
--------------------------------------------------------------------------------

================================================================================

 Patient ID: P0058
--------------------------------------------------------------------------------

 Follow-up Actions:
Outreach Plan:
1. Phone Call: Reach out to the patient via phone to discuss the missed appointment and express concern about their health. The goal is to understand the reason for missing the appointment and encourage them to schedule a new appointment.
2. Email or Secure Messaging: Send a follow-up email or secure message to the patient, reiterating the importance of regular check-ups and providi ...

================================================================================

 Patient ID: P0062
--------------------------------------------------------------------------------

 Follow-up Actions:
Outreach Plan:
1. Phone Call: Reach out to the patient via phone to confirm the missed appointment and inquire about their reason for missing it. This will help to understand their current situation and provide an opportunity to reschedule the appointment.
2. SMS/Text Message: Send a reminder text message to the patient to reschedule their appointment. This will help to re-engage the patient and e ...

================================================================================

 Patient ID: P0063
--------------------------------------------------------------------------------

 Risk Assessment:
Risk Classification:
Based on the provided patient data, I would classify the risk as HIGH.
Reason:
1. Elevated Blood Pressure: The patient's lab value for BP Systolic is 172.4 mmHg, which is significantly higher than the normal range (typically < 120 mmHg). This indicates uncontrolled hypertension, which is a major risk factor for cardiovascular disease.
2. Missed Appointment: The patient missed  ...

📋 Care Plan:
Follow-up Plan:
Risk Classification: HIGH
Reason:
1. Elevated Blood Pressure: The patient's lab value for BP Systolic is 172.4 mmHg, which is significantly higher than the normal range (typically < 120 mmHg).
2. Missed Appointment: The patient missed their last scheduled appointment, indicating a lack of adherence to their treatment plan or a lack of engagement with their healthcare provider.
3. S ...

================================================================================

 Patient ID: P0066
--------------------------------------------------------------------------------

 Follow-up Actions:
Outreach Plan:
1. Phone Call: Schedule a phone call with Angela Pereira to discuss the missed appointment and express concern about her health. The goal is to understand the reason for the missed appointment and encourage her to reschedule.
2. Email or Letter: Send a follow-up email or letter to Angela Pereira, reiterating the importance of regular appointments and the potential consequences of de ...

================================================================================

 Patient ID: P0069
--------------------------------------------------------------------------------

 Follow-up Actions:
Outreach Plan:
1. Phone Call: Reach out to the patient, Victor Lobo, via phone to discuss the missed appointment and reschedule a new appointment.
2. Text Message: Send a text message to the patient reminding them of the importance of regular check-ups and the impact of missed appointments on their health.
3. Email: Send a follow-up email to the patient with a link to reschedule an appointment and ...

================================================================================

 Patient ID: P0070
--------------------------------------------------------------------------------

 Follow-up Actions:
Patient Missed Appointment Outreach Plan
 Patient Information
 Patient ID: P0070
 Patient Name: Teresa Dias
 Age: 55
 Gender: Male
 Diagnosis: Osteoarthritis
 Current Medication: Ibuprofen 400mg
 Lab Test: Pain Score
 Lab Value: 3.6
 Lab Unit: /10
 Last Visit Date: 2024-05-16
 Next Scheduled Visit: 2024-06-30
 Days Since Last Visit: 229
 Missed Last Appointment: Yes
 Vitals:
  - BP Systolic: 126
  ...

================================================================================

 Patient ID: P0076
--------------------------------------------------------------------------------

 Follow-up Actions:
Outreach Plan:
1. Phone Call: Reach out to the patient via phone to check on their well-being and understand the reason for missing their appointment. This will help to:
	 Re-engage the patient in their care plan
	 Identify any potential barriers to care
	 Provide emotional support and reassurance
2. Text Message or Email: Send a follow-up message to the patient to remind them of their missed appo ...

================================================================================

 Patient ID: P0081
--------------------------------------------------------------------------------

 Risk Assessment:
Risk Classification: MEDIUM
Reason:
1. Elevated Blood Pressure (BP): The patient's systolic BP (157 mmHg) is above the normal range, indicating potential cardiovascular risk.
2. Missed Last Appointment: The patient missed their last scheduled appointment, which may indicate a lack of engagement with their treatment plan.
3. High TSH Level: The patient's TSH level (9.8 mIU/L) is above the normal ra ...

📋 Care Plan:
Follow-up Plan for Patient P0081 (Nandini Rao)
Urgency: Medium
Reason:
1. Elevated Blood Pressure (BP): The patient's systolic BP (157 mmHg) is above the normal range, indicating potential cardiovascular risk.
2. Missed Last Appointment: The patient missed their last scheduled appointment, which may indicate a lack of engagement with their treatment plan.
3. High TSH Level: The patient's TSH level ...

================================================================================

 Patient ID: P0098
--------------------------------------------------------------------------------

 Follow-up Actions:
Outreach Plan:
1. Phone Call: Reach out to Mrinal Basu via phone to discuss the missed appointment and understand the reason behind it. This will help in identifying potential issues and provide an opportunity for the patient to reschedule their appointment.
2. Text Message/Email: Send a reminder text message or email to Mrinal Basu to reschedule their appointment and reiterate the importance of r ...

================================================================================

 Patient ID: P0099
--------------------------------------------------------------------------------

 Follow-up Actions:
Outreach Plan:
1. Phone Call: Reach out to the patient via phone to check on their well-being and understand the reason for missing their appointment. This will help to re-engage the patient and address any concerns they may have.
2. Text Message/Email: Send a reminder text message or email to the patient to reschedule their appointment. This will help to keep the patient informed and engaged.
3.  ...

================================================================================